In [1]:
%pip install duckdb

Requirement already satisfied: duckdb in c:\users\rorym\appdata\local\programs\python\python314-arm64\lib\site-packages (1.5.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\rorym\AppData\Local\Programs\Python\Python314-arm64\python.exe -m pip install --upgrade pip

In [2]:
import duckdb

print(duckdb.__version__)

1.5.6

In [3]:
conn = duckdb.connect("procurement.duckdb")

In [4]:
conn.execute("""
    CREATE TABLE IF NOT EXISTS raw_releases (
        release_id VARCHAR PRIMARY KEY,
        ocid VARCHAR,
        release_date TIMESTAMP,
        tags JSON,
        raw_json JSON,
        ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
""")

In [5]:
conn.execute("DESCRIBE raw_releases").fetchall()

[('release_id', 'VARCHAR', 'NO', 'PRI', None, None),
 ('ocid', 'VARCHAR', 'YES', None, None, None),
 ('release_date', 'TIMESTAMP WITH TIME ZONE', 'YES', None, None, None),
 ('tags', 'JSON', 'YES', None, None, None),
 ('raw_json', 'JSON', 'YES', None, None, None),
 ('ingested_at', 'TIMESTAMP', 'YES', None, 'CURRENT_TIMESTAMP', None)]

In [6]:
import requests
url = "https://www.find-tender.service.gov.uk/api/1.0/ocdsReleasePackages"

response = requests.get(url, timeout=10)
response.raise_for_status()

data = response.json()
releases = data["releases"]

print("Releases downloaded:", len(releases))

Releases downloaded: 100

In [7]:
print(releases[0]["ocid"])
print(releases[0]["id"])
print(releases[0]["date"])
print(releases[0]["tag"])

ocds-h6vhtk-078039
093578-2026
2026-10-04T11:13:59+01:00
['award', 'contract']

In [8]:
import json

tags_json = json.dumps(releases[0]["tag"])
raw_json = json.dumps(releases[0])

print(tags_json)
print(type(tags_json))

print(raw_json[:200])
print(type(raw_json))

["award", "contract"]
<class 'str'>
{"ocid": "ocds-h6vhtk-078039", "id": "093578-2026", "tag": ["award", "contract"], "date": "2026-10-04T11:13:59+01:00", "initiationType": "tender", "parties": [{"name": "British Council", "id": "GB-PPO
<class 'str'>

In [9]:
release = releases[0]

conn.execute("""
    INSERT INTO raw_releases (
        release_id,
        ocid,
        release_date,
        tags,
        raw_json
    )
    VALUES (?, ?, ?, ?, ?)
    ON CONFLICT (release_id) DO NOTHING
""", [
    release["id"],
    release["ocid"],
    release["date"],
    json.dumps(release["tag"]),
    json.dumps(release)
])

In [10]:
result = conn.execute("""
    SELECT
        release_id,
        ocid,
        release_date,
        tags,
        ingested_at
    FROM raw_releases
""").fetchall()

print(result)

[('092770-2026', 'ocds-h6vhtk-06759b', datetime.datetime(2026, 10, 1, 11, 46, 44, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 12, 9, 56, 530408)), ('092769-2026', 'ocds-h6vhtk-077e7b', datetime.datetime(2026, 10, 1, 11, 46, 41, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tender"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 273388)), ('092768-2026', 'ocds-h6vhtk-077e7a', datetime.datetime(2026, 10, 1, 11, 46, 10, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 296854)), ('092767-2026', 'ocds-h6vhtk-06ecf6', datetime.datetime(2026, 10, 1, 11, 45, 29, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planningUpdate"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 310387)), ('092766-2026', 'ocds-h6vhtk-064e67', datetime.datetime(2026, 10, 1, 11, 44, 37, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["contractTermination"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 315645)), ('092765-2026', 'ocds-h6vhtk-077e79', datetime.datetime(2026, 10, 1, 11, 44, 29, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 320233)), ('092764-2026', 'ocds-h6vhtk-077e78', datetime.datetime(2026, 10, 1, 11, 43, 45, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 325256)), ('092763-2026', 'ocds-h6vhtk-069509', datetime.datetime(2026, 10, 1, 11, 43, 7, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planningUpdate"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 329731)), ('092762-2026', 'ocds-h6vhtk-06db97', datetime.datetime(2026, 10, 1, 11, 40, 28, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 333822)), ('092761-2026', 'ocds-h6vhtk-077e77', datetime.datetime(2026, 10, 1, 11, 38, 10, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planning"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 338057)), ('092760-2026', 'ocds-h6vhtk-077e76', datetime.datetime(2026, 10, 1, 11, 37, 15, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tender"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 342672)), ('092759-2026', 'ocds-h6vhtk-077e75', datetime.datetime(2026, 10, 1, 11, 36, 5, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tender"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 346794)), ('092758-2026', 'ocds-h6vhtk-077e74', datetime.datetime(2026, 10, 1, 11, 35, 38, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tender"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 350970)), ('092757-2026', 'ocds-h6vhtk-06d83e', datetime.datetime(2026, 10, 1, 11, 32, 49, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 355246)), ('092756-2026', 'ocds-h6vhtk-077e73', datetime.datetime(2026, 10, 1, 11, 31, 47, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 359224)), ('092755-2026', 'ocds-h6vhtk-077e72', datetime.datetime(2026, 10, 1, 11, 29, 12, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 363107)), ('092754-2026', 'ocds-h6vhtk-077e71', datetime.datetime(2026, 10, 1, 11, 28, 2, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 367050)), ('092753-2026', 'ocds-h6vhtk-077e6f', datetime.datetime(2026, 10, 1, 11, 27, 55, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 371233)), ('092752-2026', 'ocds-h6vhtk-077e70', datetime.datetime(2026, 10, 1, 11, 27, 56, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planning"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 375886)), ('092751-2026', 'ocds-h6vhtk-066174', datetime.datetime(2026, 10, 1, 11, 27, 41, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tender"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 379236)), ('092750-2026', 'ocds-h6vhtk-06fa10', datetime.datetime(2026, 10, 1, 11, 27, 10, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tenderUpdate"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 383870)), ('092749-2026', 'ocds-h6vhtk-077e57', datetime.datetime(2026, 10, 1, 11, 25, 31, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planningUpdate"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 387998)), ('092748-2026', 'ocds-h6vhtk-06fa0f', datetime.datetime(2026, 10, 1, 11, 25, 14, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tenderUpdate"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 391948)), ('092747-2026', 'ocds-h6vhtk-0694d0', datetime.datetime(2026, 10, 1, 11, 23, 11, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 399779)), ('092746-2026', 'ocds-h6vhtk-0779fd', datetime.datetime(2026, 10, 1, 11, 23, 2, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 402831)), ('092745-2026', 'ocds-h6vhtk-077e6e', datetime.datetime(2026, 10, 1, 11, 21, 51, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tender"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 405964)), ('092744-2026', 'ocds-h6vhtk-077e6d', datetime.datetime(2026, 10, 1, 11, 20, 30, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 409225)), ('092743-2026', 'ocds-h6vhtk-077e6c', datetime.datetime(2026, 10, 1, 11, 20, 22, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 412194)), ('092742-2026', 'ocds-h6vhtk-06c020', datetime.datetime(2026, 10, 1, 11, 19, 38, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 414697)), ('092741-2026', 'ocds-h6vhtk-077e6b', datetime.datetime(2026, 10, 1, 11, 18, 36, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 418281)), ('092740-2026', 'ocds-h6vhtk-077e6a', datetime.datetime(2026, 10, 1, 11, 17, 40, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 421018)), ('092739-2026', 'ocds-h6vhtk-077e69', datetime.datetime(2026, 10, 1, 11, 15, 37, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 424359)), ('092738-2026', 'ocds-h6vhtk-06f8dd', datetime.datetime(2026, 10, 1, 11, 15, 29, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 427203)), ('092737-2026', 'ocds-h6vhtk-077e68', datetime.datetime(2026, 10, 1, 11, 12, 50, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 429272)), ('092736-2026', 'ocds-h6vhtk-077e67', datetime.datetime(2026, 10, 1, 11, 12, 15, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 432262)), ('092735-2026', 'ocds-h6vhtk-077e66', datetime.datetime(2026, 10, 1, 11, 11, 7, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 435196)), ('092734-2026', 'ocds-h6vhtk-077e65', datetime.datetime(2026, 10, 1, 11, 10, 34, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 438366)), ('092733-2026', 'ocds-h6vhtk-06f8dc', datetime.datetime(2026, 10, 1, 11, 10, 21, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 441760)), ('092732-2026', 'ocds-h6vhtk-077e64', datetime.datetime(2026, 10, 1, 11, 10, 6, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 444590)), ('092731-2026', 'ocds-h6vhtk-077e63', datetime.datetime(2026, 10, 1, 11, 9, 5, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 447687)), ('092730-2026', 'ocds-h6vhtk-077e62', datetime.datetime(2026, 10, 1, 11, 8, 14, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 452138)), ('092729-2026', 'ocds-h6vhtk-077e57', datetime.datetime(2026, 10, 1, 11, 7, 55, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planningUpdate"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 455769)), ('092728-2026', 'ocds-h6vhtk-077e61', datetime.datetime(2026, 10, 1, 11, 6, 59, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planning"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 459471)), ('092727-2026', 'ocds-h6vhtk-077e60', datetime.datetime(2026, 10, 1, 11, 6, 41, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 464147)), ('092726-2026', 'ocds-h6vhtk-06da77', datetime.datetime(2026, 10, 1, 11, 2, 52, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 466799)), ('092725-2026', 'ocds-h6vhtk-068a76', datetime.datetime(2026, 10, 1, 11, 2, 38, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tenderUpdate"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 469937)), ('092724-2026', 'ocds-h6vhtk-077e5f', datetime.datetime(2026, 10, 1, 11, 0, 11, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 473649)), ('092723-2026', 'ocds-h6vhtk-06ec55', datetime.datetime(2026, 10, 1, 10, 58, 53, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tender"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 476920)), ('092722-2026', 'ocds-h6vhtk-077e5e', datetime.datetime(2026, 10, 1, 10, 58, 33, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 480552)), ('092721-2026', 'ocds-h6vhtk-077e5d', datetime.datetime(2026, 10, 1, 10, 56, 17, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 484330)), ('092720-2026', 'ocds-h6vhtk-077e5c', datetime.datetime(2026, 10, 1, 10, 56, 8, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 488300)), ('092719-2026', 'ocds-h6vhtk-077e5b', datetime.datetime(2026, 10, 1, 10, 54, 36, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 492288)), ('092718-2026', 'ocds-h6vhtk-077e5a', datetime.datetime(2026, 10, 1, 10, 52, 23, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tender"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 496508)), ('092717-2026', 'ocds-h6vhtk-055641', datetime.datetime(2026, 10, 1, 10, 50, 43, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["contractAmendment"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 500754)), ('092716-2026', 'ocds-h6vhtk-077dcf', datetime.datetime(2026, 10, 1, 10, 49, 39, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 505198)), ('092715-2026', 'ocds-h6vhtk-077e59', datetime.datetime(2026, 10, 1, 10, 48, 2, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planning"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 508810)), ('092714-2026', 'ocds-h6vhtk-077e58', datetime.datetime(2026, 10, 1, 10, 47, 21, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planning"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 512212)), ('092713-2026', 'ocds-h6vhtk-077e57', datetime.datetime(2026, 10, 1, 10, 47, 10, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planning"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 516684)), ('092712-2026', 'ocds-h6vhtk-077e56', datetime.datetime(2026, 10, 1, 10, 45, 51, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 520593)), ('092711-2026', 'ocds-h6vhtk-077e4d', datetime.datetime(2026, 10, 1, 10, 45, 28, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 524090)), ('092710-2026', 'ocds-h6vhtk-077e55', datetime.datetime(2026, 10, 1, 10, 45, 5, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 527903)), ('092709-2026', 'ocds-h6vhtk-077e54', datetime.datetime(2026, 10, 1, 10, 43, 40, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 531009)), ('092708-2026', 'ocds-h6vhtk-077e53', datetime.datetime(2026, 10, 1, 10, 41, 38, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 534505)), ('092707-2026', 'ocds-h6vhtk-077e52', datetime.datetime(2026, 10, 1, 10, 41, 2, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 537363)), ('092706-2026', 'ocds-h6vhtk-0774e0', datetime.datetime(2026, 10, 1, 10, 40, 3, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 540549)), ('092705-2026', 'ocds-h6vhtk-077e51', datetime.datetime(2026, 10, 1, 10, 39, 48, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 544856)), ('092704-2026', 'ocds-h6vhtk-067c3b', datetime.datetime(2026, 10, 1, 10, 39, 17, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 549180)), ('092703-2026', 'ocds-h6vhtk-077e50', datetime.datetime(2026, 10, 1, 10, 38, 46, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tenderUpdate"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 554647)), ('092702-2026', 'ocds-h6vhtk-029897', datetime.datetime(2026, 10, 1, 10, 37, 42, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 558680)), ('092701-2026', 'ocds-h6vhtk-077e4f', datetime.datetime(2026, 10, 1, 10, 36, 10, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planning"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 563068)), ('092700-2026', 'ocds-h6vhtk-05d16b', datetime.datetime(2026, 10, 1, 10, 34, 51, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tenderCancellation"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 567818)), ('092699-2026', 'ocds-h6vhtk-077e4e', datetime.datetime(2026, 10, 1, 10, 33, 44, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 571835)), ('092698-2026', 'ocds-h6vhtk-077e4d', datetime.datetime(2026, 10, 1, 10, 33, 5, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 575736)), ('092697-2026', 'ocds-h6vhtk-069003', datetime.datetime(2026, 10, 1, 10, 32, 28, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tenderCancellation"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 579545)), ('092696-2026', 'ocds-h6vhtk-031f31', datetime.datetime(2026, 10, 1, 10, 29, 31, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 583545)), ('092695-2026', 'ocds-h6vhtk-077e4c', datetime.datetime(2026, 10, 1, 10, 29, 36, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 587621)), ('092694-2026', 'ocds-h6vhtk-067905', datetime.datetime(2026, 10, 1, 10, 29, 32, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 591604)), ('092693-2026', 'ocds-h6vhtk-06bb54', datetime.datetime(2026, 10, 1, 10, 28, 12, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 596056)), ('092692-2026', 'ocds-h6vhtk-077e4b', datetime.datetime(2026, 10, 1, 10, 26, 36, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 600166)), ('092691-2026', 'ocds-h6vhtk-077e4a', datetime.datetime(2026, 10, 1, 10, 23, 23, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tender"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 603795)), ('092690-2026', 'ocds-h6vhtk-051281', datetime.datetime(2026, 10, 1, 10, 23, 6, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planningUpdate"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 607468)), ('092689-2026', 'ocds-h6vhtk-077e49', datetime.datetime(2026, 10, 1, 10, 22, 59, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 611752)), ('092688-2026', 'ocds-h6vhtk-077e40', datetime.datetime(2026, 10, 1, 10, 20, 44, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 615679)), ('092687-2026', 'ocds-h6vhtk-077e48', datetime.datetime(2026, 10, 1, 10, 20, 14, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tender"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 619745)), ('092686-2026', 'ocds-h6vhtk-067751', datetime.datetime(2026, 10, 1, 10, 16, 48, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tenderUpdate"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 624576)), ('092685-2026', 'ocds-h6vhtk-077e47', datetime.datetime(2026, 10, 1, 10, 16, 25, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 628972)), ('092684-2026', 'ocds-h6vhtk-077e46', datetime.datetime(2026, 10, 1, 10, 15, 16, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 632723)), ('092683-2026', 'ocds-h6vhtk-06ed16', datetime.datetime(2026, 10, 1, 10, 13, 57, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tenderUpdate"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 636775)), ('092682-2026', 'ocds-h6vhtk-06896d', datetime.datetime(2026, 10, 1, 10, 13, 18, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planningUpdate"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 640953)), ('092681-2026', 'ocds-h6vhtk-077e45', datetime.datetime(2026, 10, 1, 10, 13, 11, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 645114)), ('092680-2026', 'ocds-h6vhtk-077e44', datetime.datetime(2026, 10, 1, 10, 12, 49, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 649006)), ('092679-2026', 'ocds-h6vhtk-051f7e', datetime.datetime(2026, 10, 1, 10, 11, 56, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 653531)), ('092678-2026', 'ocds-h6vhtk-077e43', datetime.datetime(2026, 10, 1, 10, 11, 25, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["award", "contract"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 657382)), ('092677-2026', 'ocds-h6vhtk-077e42', datetime.datetime(2026, 10, 1, 10, 10, 45, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["tender"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 661495)), ('092676-2026', 'ocds-h6vhtk-06ecf6', datetime.datetime(2026, 10, 1, 10, 10, 18, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '["planning"]', datetime.datetime(2026, 10, 1, 13, 54, 42, 665957)), ('092675-2026', 'ocds-h6vhtk-077e41', datetime.datetime(2026, 10, 1, 10, 9, 15, tzinfo=<DstTzInfo 'Europe/London' BST+1

In [11]:
release = releases[0]

conn.execute("""
    INSERT INTO raw_releases (
        release_id,
        ocid,
        release_date,
        tags,
        raw_json
    )
    VALUES (?, ?, ?, ?, ?)
    ON CONFLICT (release_id) DO NOTHING
""", [
    release["id"],
    release["ocid"],
    release["date"],
    json.dumps(release["tag"]),
    json.dumps(release)
])

In [12]:
count = conn.execute("""
    SELECT COUNT(*)
    FROM raw_releases
""").fetchone()[0]

print("Rows:", count)

Rows: 1166

In [13]:
for release in releases:

    conn.execute("""
        INSERT INTO raw_releases (
            release_id,
            ocid,
            release_date,
            tags,
            raw_json
        )
        VALUES (?, ?, ?, ?, ?)
        ON CONFLICT (release_id) DO NOTHING
    """, [
        release["id"],
        release["ocid"],
        release["date"],
        json.dumps(release["tag"]),
        json.dumps(release)
    ])

In [14]:
count = conn.execute("""
    SELECT COUNT(*)
    FROM raw_releases
""").fetchone()[0]

print("Rows:", count)

Rows: 1166

In [15]:
url = "https://www.find-tender.service.gov.uk/api/1.0/ocdsReleasePackages"

page = 1
max_pages = 5

while url and page <= max_pages:

    response = requests.get(url, timeout=10)
    response.raise_for_status()

    data = response.json()
    releases = data["releases"]

    for release in releases:

        conn.execute("""
        INSERT INTO raw_releases (
            release_id,
            ocid,
            release_date,
            tags,
            raw_json
        )
        VALUES (?, ?, ?, ?, ?)
        ON CONFLICT (release_id) DO NOTHING
    """, [
        release["id"],
        release["ocid"],
        release["date"],
        json.dumps(release["tag"]),
        json.dumps(release)
    ])

    url = data["links"].get("next")

    page += 1

In [16]:
count = conn.execute("""
    SELECT COUNT(*)
    FROM raw_releases
""").fetchone()[0]

print("Rows:", count)

Rows: 1166

In [17]:
url = "https://www.find-tender.service.gov.uk/api/1.0/ocdsReleasePackages"

page = 1
max_pages = 5

while url and page <= max_pages:

    response = requests.get(url, timeout=10)
    response.raise_for_status()

    data = response.json()
    releases = data["releases"]

    for release in releases:

        conn.execute("""
        INSERT INTO raw_releases (
            release_id,
            ocid,
            release_date,
            tags,
            raw_json
        )
        VALUES (?, ?, ?, ?, ?)
        ON CONFLICT (release_id) DO NOTHING
    """, [
        release["id"],
        release["ocid"],
        release["date"],
        json.dumps(release["tag"]),
        json.dumps(release)
    ])

    url = data["links"].get("next")

    page += 1

In [18]:
count = conn.execute("""
    SELECT COUNT(*)
    FROM raw_releases
""").fetchone()[0]

print("Rows:", count)

Rows: 1166

In [19]:
conn.execute("""
    SELECT
        release_id,
        ocid,
        release_date,
        ingested_at
    FROM raw_releases
    ORDER BY ingested_at DESC
    LIMIT 10
""").fetchall()

[('093074-2026',
  'ocds-h6vhtk-077f22',
  datetime.datetime(2026, 10, 2, 7, 47, 47, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>),
  datetime.datetime(2026, 10, 4, 13, 25, 8, 254802)),
 ('093075-2026',
  'ocds-h6vhtk-06f5ce',
  datetime.datetime(2026, 10, 2, 7, 47, 55, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>),
  datetime.datetime(2026, 10, 4, 13, 25, 8, 252376)),
 ('093076-2026',
  'ocds-h6vhtk-067bb5',
  datetime.datetime(2026, 10, 2, 7, 57, 4, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>),
  datetime.datetime(2026, 10, 4, 13, 25, 8, 249567)),
 ('093077-2026',
  'ocds-h6vhtk-077f23',
  datetime.datetime(2026, 10, 2, 8, 2, 37, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>),
  datetime.datetime(2026, 10, 4, 13, 25, 8, 247267)),
 ('093078-2026',
  'ocds-h6vhtk-077f24',
  datetime.datetime(2026, 10, 2, 8, 5, 5, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>),
  datetime.datetime(2026, 10, 4, 13, 25, 8, 244881)),
 ('093079-2026',
  'ocds-h6vhtk-077f23',
  datetime.datetime(2026, 10, 2, 8, 7, 31, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>),
  datetime.datetime(2026, 10, 4, 13, 25, 8, 242493)),
 ('093080-2026',
  'ocds-h6vhtk-0775d3',
  datetime.datetime(2026, 10, 2, 8, 13, 20, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>),
  datetime.datetime(2026, 10, 4, 13, 25, 8, 240189)),
 ('093081-2026',
  'ocds-h6vhtk-077f25',
  datetime.datetime(2026, 10, 2, 8, 16, 10, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>),
  datetime.datetime(2026, 10, 4, 13, 25, 8, 237923)),
 ('093082-2026',
  'ocds-h6vhtk-06bffe',
  datetime.datetime(2026, 10, 2, 8, 19, 17, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>),
  datetime.datetime(2026, 10, 4, 13, 25, 8, 235481)),
 ('093083-2026',
  'ocds-h6vhtk-077f26',
  datetime.datetime(2026, 10, 2, 8, 24, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>),
  datetime.datetime(2026, 10, 4, 13, 25, 8, 233168))]

In [20]:
watermark = conn.execute("""
    SELECT MAX(release_date)
    FROM raw_releases
""").fetchone()[0]

print("Current watermark:", watermark)

Current watermark: 2026-10-04 11:13:59+01:00

In [21]:
watermark_str = watermark.isoformat()

print(watermark_str)

2026-10-04T11:13:59+01:00

In [22]:
url = "https://www.find-tender.service.gov.uk/api/1.0/ocdsReleasePackages"

params = {
    "updatedFrom": watermark_str
}

response = requests.get(
    url,
    params=params,
    timeout=10
)

response.raise_for_status()

incremental_data = response.json()
incremental_releases = incremental_data["releases"]

print("Request URL:", response.url)
print("Releases returned:", len(incremental_releases))

Request URL: https://www.find-tender.service.gov.uk/api/1.0/ocdsReleasePackages?updatedFrom=2026-10-04T11%3A13%3A59%2B01%3A00
Releases returned: 1

In [23]:
dates = [release["date"] for release in incremental_releases]

print("First:", dates[0])
print("Last:", dates[-1])
print("Minimum:", min(dates))
print("Maximum:", max(dates))
print("Next page:", incremental_data.get("links", {}).get("next"))

First: 2026-10-04T11:13:59+01:00
Last: 2026-10-04T11:13:59+01:00
Minimum: 2026-10-04T11:13:59+01:00
Maximum: 2026-10-04T11:13:59+01:00
Next page: None

In [24]:
conn.execute("""
    ALTER TABLE raw_releases
    ALTER COLUMN release_date TYPE TIMESTAMPTZ
""")

In [25]:
conn.execute("DESCRIBE raw_releases").fetchall()

[('release_id', 'VARCHAR', 'NO', 'PRI', None, None),
 ('ocid', 'VARCHAR', 'YES', None, None, None),
 ('release_date', 'TIMESTAMP WITH TIME ZONE', 'YES', None, None, None),
 ('tags', 'JSON', 'YES', None, None, None),
 ('raw_json', 'JSON', 'YES', None, None, None),
 ('ingested_at', 'TIMESTAMP', 'YES', None, 'CURRENT_TIMESTAMP', None)]

In [26]:
url = "https://www.find-tender.service.gov.uk/api/1.0/ocdsReleasePackages"

params = {
    "updatedFrom": watermark.isoformat()
}

incremental_releases = []
page = 1

while url:

    print(f"Downloading page {page}...")
    response = requests.get(
        url,
        params=params,
        timeout=10
    )
    response.raise_for_status()

    incremental_data = response.json()
    
    incremental_releases.extend(incremental_data["releases"])
    url = incremental_data.get("links", {}).get("next")
    params = None
    page += 1
    
print("Total incremental releases:", len(incremental_releases))

Downloading page 1...
Total incremental releases: 1

In [27]:
print("Number of releases:", len(incremental_releases))

dates = [release["date"] for release in incremental_releases]

print("Earliest:", min(dates))
print("Latest:", max(dates))

Number of releases: 1
Earliest: 2026-10-04T11:13:59+01:00
Latest: 2026-10-04T11:13:59+01:00

In [28]:
existing_count = 0

for release in incremental_releases:
    result = conn.execute("""
        SELECT COUNT(*)
        FROM raw_releases
        WHERE release_id = ?
    """, [release["id"]]).fetchone()[0]

    if result > 0:
        existing_count += 1

print("Already in DuckDB:", existing_count)
print("Potentially new:", len(incremental_releases) - existing_count)

Already in DuckDB: 1
Potentially new: 0

In [29]:
url = "https://www.find-tender.service.gov.uk/api/1.0/ocdsReleasePackages"

params = {
    "updatedFrom": watermark.isoformat()
}

incremental_releases = []
page = 1
processed = 0
while url:

    print(f"Downloading page {page}...")
    response = requests.get(
        url,
        params=params,
        timeout=10
    )
    response.raise_for_status()

    incremental_data = response.json()

    for release in incremental_data["releases"]:
        processed += 1
        conn.execute("""
        INSERT INTO raw_releases (
            release_id,
            ocid,
            release_date,
            tags,
            raw_json
        )
        VALUES (?, ?, ?, ?, ?)
        ON CONFLICT (release_id) DO NOTHING
    """, [
        release["id"],
        release["ocid"],
        release["date"],
        json.dumps(release["tag"]),
        json.dumps(release)
    ])
    
    url = incremental_data.get("links", {}).get("next")
    params = None
    page += 1
    
print("processed:", processed)

Downloading page 1...
processed: 1

In [30]:
count = conn.execute("""
    SELECT COUNT(*)
    FROM raw_releases
""").fetchone()[0]

print("Total rows:", count)

Total rows: 1166

In [63]:
## Refactoring the pipeline
def get_watermark():
    with duckdb.connect("procurement.duckdb") as conn:

        result = conn.execute("""
            SELECT watermark_to
            FROM pipeline_runs
            WHERE pipeline_name = 'procurement_ingestion'
              AND status = 'SUCCESS'
            ORDER BY completed_at DESC
            LIMIT 1
        """).fetchone()

        if result is not None:
            watermark = result[0]
        else:
            watermark = conn.execute("""
                SELECT MAX(release_date)
                FROM raw_releases
            """).fetchone()[0]

    return watermark

In [64]:
watermark = get_watermark()
print(watermark)

2026-10-04 14:29:57+01:00

In [36]:
def extract_releases(watermark):
    url = "https://www.find-tender.service.gov.uk/api/1.0/ocdsReleasePackages"

    params = {
        "updatedFrom": watermark.isoformat()
    }
    
    incremental_releases = []
    page = 1

    while url:
        response = requests.get(
            url,
            params=params,
            timeout=10
        )
        response.raise_for_status()
        print(f"Downloading page {page}...")
        incremental_data = response.json()
        incremental_releases.extend(incremental_data["releases"])
        
        
        url = incremental_data.get("links", {}).get("next")
        params = None
        page += 1

    return incremental_releases

In [37]:
watermark = get_watermark()

releases = extract_releases(watermark)

print("Extracted:", len(releases))

Downloading page 1...
Extracted: 3

In [46]:
def load_releases(releases):
    with duckdb.connect("procurement.duckdb") as conn:
        before_count = conn.execute("""
        SELECT COUNT(*)
        FROM raw_releases
        """).fetchone()[0]
        processed = 0
        for release in releases:
            processed += 1
            conn.execute("""
            INSERT INTO raw_releases (
                release_id,
                ocid,
                release_date,
                tags,
                raw_json
            )
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT (release_id) DO NOTHING
            """, [
            release["id"],
            release["ocid"],
            release["date"],
            json.dumps(release["tag"]),
            json.dumps(release)
        ])
        after_count = conn.execute("""
        SELECT COUNT(*)
        FROM raw_releases
        """).fetchone()[0]
    inserted = after_count - before_count
    skipped = processed - inserted

    return processed, inserted, skipped

In [40]:
watermark = get_watermark()

releases = extract_releases(watermark)

processed = load_releases(releases)

print("Watermark:", watermark)
print("Extracted:", len(releases))
print("Processed:", processed)

Downloading page 1...
Watermark: 2026-10-04 11:13:59+01:00
Extracted: 3
Processed: 3

In [41]:
count = duckdb.connect("procurement.duckdb").execute("""
    SELECT COUNT(*)
    FROM raw_releases
""").fetchone()[0]

print("Total rows:", count)

Total rows: 1168

In [47]:
watermark = get_watermark()
releases = extract_releases(watermark)
processed, inserted, skipped = load_releases(releases)

print("Processed:", processed)
print("Inserted:", inserted)
print("Skipped:", skipped)

Downloading page 1...
Processed: 1
Inserted: 0
Skipped: 1

In [49]:
with duckdb.connect("procurement.duckdb") as conn:
    conn.execute("""
        CREATE TABLE IF NOT EXISTS pipeline_runs (
            run_id VARCHAR PRIMARY KEY,
            pipeline_name VARCHAR,
            started_at TIMESTAMPTZ,
            completed_at TIMESTAMPTZ,
            watermark_from TIMESTAMPTZ,
            watermark_to TIMESTAMPTZ,
            rows_extracted INTEGER,
            rows_inserted INTEGER,
            rows_skipped INTEGER,
            status VARCHAR
        )
    """)

In [50]:
with duckdb.connect("procurement.duckdb") as conn:
    result = conn.execute("""
        DESCRIBE pipeline_runs
    """).fetchall()

result

[('run_id', 'VARCHAR', 'NO', 'PRI', None, None),
 ('pipeline_name', 'VARCHAR', 'YES', None, None, None),
 ('started_at', 'TIMESTAMP WITH TIME ZONE', 'YES', None, None, None),
 ('completed_at', 'TIMESTAMP WITH TIME ZONE', 'YES', None, None, None),
 ('watermark_from', 'TIMESTAMP WITH TIME ZONE', 'YES', None, None, None),
 ('watermark_to', 'TIMESTAMP WITH TIME ZONE', 'YES', None, None, None),
 ('rows_extracted', 'INTEGER', 'YES', None, None, None),
 ('rows_inserted', 'INTEGER', 'YES', None, None, None),
 ('rows_skipped', 'INTEGER', 'YES', None, None, None),
 ('status', 'VARCHAR', 'YES', None, None, None)]

In [51]:
import uuid
run_id = str(uuid.uuid4())

print(run_id)

b49f4547-dd06-44e7-ba82-775a43ba9724

In [52]:
def start_pipeline_run(watermark):
    with duckdb.connect("procurement.duckdb") as conn:
        run_id = str(uuid.uuid4())
        conn.execute("""
            INSERT INTO pipeline_runs (
                run_id,
                pipeline_name,
                started_at,
                watermark_from,
                status
            )
            VALUES (?, ?, CURRENT_TIMESTAMP, ?, ?)
            """, [
            run_id,
            'procurement_ingestion',
            watermark,
            'RUNNING'
        ])
        return run_id

In [53]:
watermark = get_watermark()

run_id = start_pipeline_run(watermark)

print("Run ID:", run_id)

Run ID: 534c15cd-8f0c-4e1e-8d58-23400f8efbcc

In [54]:
with duckdb.connect("procurement.duckdb") as conn:
    result = conn.execute("""
        SELECT *
        FROM pipeline_runs
        WHERE run_id = ?
    """, [run_id]).fetchone()

print(result)

('534c15cd-8f0c-4e1e-8d58-23400f8efbcc', 'procurement_ingestion', datetime.datetime(2026, 10, 4, 19, 46, 19, 203101, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), None, datetime.datetime(2026, 10, 4, 14, 29, 57, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), None, None, None, None, 'RUNNING')

In [55]:
def complete_pipeline_run(
    run_id,
    watermark_to,
    rows_extracted,
    rows_inserted,
    rows_skipped
):
    with duckdb.connect("procurement.duckdb") as conn:
        conn.execute("""
            UPDATE pipeline_runs
            SET
                completed_at = CURRENT_TIMESTAMP,
                watermark_to = ?,
                rows_extracted = ?,
                rows_inserted = ?,
                rows_skipped = ?,
                status = 'SUCCESS'
            WHERE run_id = ?
            """, [
            watermark_to,
            rows_extracted,
            rows_inserted,
            rows_skipped,
            run_id
        ])

In [58]:
from datetime import datetime
if releases:
    watermark_to = max(
        datetime.fromisoformat(release["date"])
        for release in releases
    )
else:
    watermark_to = watermark

print(watermark_to)
print(type(watermark_to))

2026-10-04 14:29:57+01:00
<class 'datetime.datetime'>

In [59]:
with duckdb.connect("procurement.duckdb") as conn:
    running_run = conn.execute("""
        SELECT
            run_id,
            watermark_from
        FROM pipeline_runs
        WHERE status = 'RUNNING'
        ORDER BY started_at DESC
        LIMIT 1
    """).fetchone()

print(running_run)

('534c15cd-8f0c-4e1e-8d58-23400f8efbcc', datetime.datetime(2026, 10, 4, 14, 29, 57, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>))

In [60]:
run_id = running_run[0]
watermark = running_run[1]

print("Run ID:", run_id)
print("Watermark from:", watermark)

Run ID: 534c15cd-8f0c-4e1e-8d58-23400f8efbcc
Watermark from: 2026-10-04 14:29:57+01:00

In [61]:
complete_pipeline_run(
    run_id,
    watermark_to,
    len(releases),
    inserted,
    skipped
)

In [62]:
with duckdb.connect("procurement.duckdb") as conn:
    result = conn.execute("""
        SELECT *
        FROM pipeline_runs
        WHERE run_id = ?
    """, [run_id]).fetchone()

print(result)

('534c15cd-8f0c-4e1e-8d58-23400f8efbcc', 'procurement_ingestion', datetime.datetime(2026, 10, 4, 19, 46, 19, 203101, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), datetime.datetime(2026, 10, 4, 20, 14, 59, 257281, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), datetime.datetime(2026, 10, 4, 14, 29, 57, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), datetime.datetime(2026, 10, 4, 14, 29, 57, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), 1, 0, 1, 'SUCCESS')

In [83]:
def run_pipeline():

    watermark = get_watermark()
    print("Watermark from:", watermark)

    run_id = start_pipeline_run(watermark)
    print("Run ID:", run_id)

    try:
        releases = extract_releases(watermark)
        print("Extracted:", len(releases))

        processed, inserted, skipped = load_releases(releases)

        print("Processed:", processed)
        print("Inserted:", inserted)
        print("Skipped:", skipped)

        if releases:
            watermark_to = max(
                datetime.fromisoformat(release["date"])
                for release in releases
            )
        else:
            watermark_to = watermark

        print("Watermark to:", watermark_to)

        complete_pipeline_run(
            run_id,
            watermark_to,
            len(releases),
            inserted,
            skipped
        )
    
        print("Pipeline completed successfully")
    except Exception:
        fail_pipeline_run(run_id)
        print("Pipeline failed!")
        raise

In [84]:
run_pipeline()

Watermark from: 2026-10-04 18:52:05+01:00
Run ID: 24680ffe-814c-455d-925d-8ff5300ec7cc
Downloading page 1...
Extracted: 1
Processed: 1
Inserted: 0
Skipped: 1
Watermark to: 2026-10-04 18:52:05+01:00
Pipeline completed successfully

In [85]:
with duckdb.connect("procurement.duckdb") as conn:
    results = conn.execute("""
        SELECT *
        FROM pipeline_runs
        ORDER BY started_at DESC
    """).df()

results

,run_id,pipeline_name,started_at,completed_at,watermark_from,watermark_to,rows_extracted,rows_inserted,rows_skipped,status
0,24680ffe-814c-455d-925d-8ff5300ec7cc,procurement_ingestion,2026-10-04 21:32:27.653057+01:00,2026-10-04 21:32:28.399111+01:00,2026-10-04 18:52:05+01:00,2026-10-04 18:52:05+01:00,1,0,1,SUCCESS
1,250a024e-4a9a-4022-8c56-3f0fba6bc702,procurement_ingestion,2026-10-04 21:19:27.707741+01:00,2026-10-04 21:19:27.712505+01:00,2026-10-04 18:52:05+01:00,NaT,<NA>,<NA>,<NA>,FAILED
2,30723c89-fd98-4fff-bdbc-5762b2700f9f,procurement_ingestion,2026-10-04 21:18:07.231051+01:00,NaT,2026-10-04 18:52:05+01:00,NaT,<NA>,<NA>,<NA>,RUNNING
3,2e250e06-17a0-45a0-90f8-aece2ab5df33,procurement_ingestion,2026-10-04 21:13:14.156645+01:00,2026-10-04 21:13:15.030846+01:00,2026-10-04 18:52:05+01:00,2026-10-04 18:52:05+01:00,1,0,1,SUCCESS
4,bd702418-d93d-4c0f-af25-75fe59c72076,procurement_ingestion,2026-10-04 21:12:49.326771+01:00,2026-10-04 21:12:50.137397+01:00,2026-10-04 18:52:05+01:00,2026-10-04 18:52:05+01:00,1,0,1,SUCCESS
5,334f7fc5-322b-4789-abf2-2e2ae3c404df,procurement_ingestion,2026-10-04 20:50:09.398674+01:00,2026-10-04 20:50:10.314728+01:00,2026-10-04 14:29:57+01:00,2026-10-04 18:52:05+01:00,3,2,1,SUCCESS
6,534c15cd-8f0c-4e1e-8d58-23400f8efbcc,procurement_ingestion,2026-10-04 19:46:19.203101+01:00,2026-10-04 20:14:59.257281+01:00,2026-10-04 14:29:57+01:00,2026-10-04 14:29:57+01:00,1,0,1,SUCCESS

In [82]:
def fail_pipeline_run(run_id):
    with duckdb.connect("procurement.duckdb") as conn:
        conn.execute("""
            UPDATE pipeline_runs
            SET
            completed_at = CURRENT_TIMESTAMP,
            status = 'FAILED'
            WHERE run_id = ?
            """, [
            run_id
            ])

In [86]:
print(get_watermark())

2026-10-04 18:52:05+01:00

In [81]:
with duckdb.connect("procurement.duckdb") as conn:
    recent_runs = conn.execute("""
        SELECT
            run_id,
            started_at,
            completed_at,
            watermark_from,
            watermark_to,
            rows_extracted,
            rows_inserted,
            rows_skipped,
            status
        FROM pipeline_runs
        ORDER BY started_at DESC
        LIMIT 5
    """).df()

recent_runs

,run_id,started_at,completed_at,watermark_from,watermark_to,rows_extracted,rows_inserted,rows_skipped,status
0,250a024e-4a9a-4022-8c56-3f0fba6bc702,2026-10-04 21:19:27.707741+01:00,2026-10-04 21:19:27.712505+01:00,2026-10-04 18:52:05+01:00,NaT,<NA>,<NA>,<NA>,FAILED
1,30723c89-fd98-4fff-bdbc-5762b2700f9f,2026-10-04 21:18:07.231051+01:00,NaT,2026-10-04 18:52:05+01:00,NaT,<NA>,<NA>,<NA>,RUNNING
2,2e250e06-17a0-45a0-90f8-aece2ab5df33,2026-10-04 21:13:14.156645+01:00,2026-10-04 21:13:15.030846+01:00,2026-10-04 18:52:05+01:00,2026-10-04 18:52:05+01:00,1,0,1,SUCCESS
3,bd702418-d93d-4c0f-af25-75fe59c72076,2026-10-04 21:12:49.326771+01:00,2026-10-04 21:12:50.137397+01:00,2026-10-04 18:52:05+01:00,2026-10-04 18:52:05+01:00,1,0,1,SUCCESS
4,334f7fc5-322b-4789-abf2-2e2ae3c404df,2026-10-04 20:50:09.398674+01:00,2026-10-04 20:50:10.314728+01:00,2026-10-04 14:29:57+01:00,2026-10-04 18:52:05+01:00,3,2,1,SUCCESS

In [2]:
conn.close()

NameError: name 'conn' is not defined

In [2]:
import requests
params = {
    "updatedFrom": "2026-10-04T18:52:05+01:00",
    "updatedTo": "2026-10-05T18:52:05+01:00"
}

response = requests.get(
    "https://www.find-tender.service.gov.uk/api/1.0/ocdsReleasePackages",
    params=params,
    timeout=30
)

print(response.status_code)

200

In [4]:
import duckdb
with duckdb.connect("procurement.duckdb") as conn:
    recent_runs = conn.execute("""
        SELECT
            run_id,
            started_at,
            completed_at,
            watermark_from,
            watermark_to,
            rows_extracted,
            rows_inserted,
            rows_skipped,
            status
        FROM pipeline_runs
        ORDER BY started_at DESC
        LIMIT 5
    """).df()

recent_runs

,run_id,started_at,completed_at,watermark_from,watermark_to,rows_extracted,rows_inserted,rows_skipped,status
0,4ef8c9df-a574-4a6a-8051-311edada9226,2026-10-22 21:05:50.844673+01:00,2026-10-22 21:05:51.694377+01:00,2026-10-22 20:56:12.372816+01:00,2026-10-22 21:05:50.899011+01:00,1,1,0,SUCCESS
1,4d72bf45-3442-4fb8-9bbc-78502cc80828,2026-10-22 20:56:12.318369+01:00,2026-10-22 21:04:06.339963+01:00,2026-10-04 18:52:05+01:00,2026-10-22 20:56:12.372816+01:00,6465,4200,2265,SUCCESS
2,1b126398-c802-4edf-8e33-0db8f070e39b,2026-10-22 20:48:33.729115+01:00,2026-10-22 20:51:48.001061+01:00,2026-10-04 18:52:05+01:00,NaT,<NA>,<NA>,<NA>,FAILED
3,1d43fdf9-a2df-4963-9c10-ea550a2df7a1,2026-10-22 20:38:41.330253+01:00,2026-10-22 20:39:38.339344+01:00,2026-10-04 18:52:05+01:00,NaT,<NA>,<NA>,<NA>,FAILED
4,9d09d4c5-d757-4566-8f95-61bc94962e51,2026-10-22 20:32:20.357029+01:00,2026-10-22 20:32:56.208632+01:00,2026-10-04 18:52:05+01:00,NaT,<NA>,<NA>,<NA>,FAILED